# frozen_string_literal: true

source "https://rubygems.org" do
  gem "verus-gem", path: "../verus-gem"

  gem "ffi", "~> 1.9", ">= 1.9.10"
  gem "sinatra", "~> 1.4", ">= 1.4.7"
  gem "sinatra-cors", "~> 1.1"
end
